export const CART_ADD_ITEM = "CART.ADD_ITEM";
export const CART_REMOVE_ITEM = "CART.REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART.SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART.SAVE_PAYMENT_METHOD";
