export const ORDER_CREATE_REQUEST = "ORDER.CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER.CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER.CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER.DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER.DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER.DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER.PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER.PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER.PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER.PAY_RESET";

export const ORDER_LIST_MY_REQUEST = "ORDER.LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER.LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER.LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER.LIST_MY_RESET";

export const ORDER_LIST_REQUEST = "ORDER.LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER.LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER.LIST_FAIL";


export const ORDER_DELIVER_REQUEST = "ORDER.DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER.DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER.DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER.DELIVER_RESET";
