export const PRODUCT_LIST_REQUEST = "PRODUCT.LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT.LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT.LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT.DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT.DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT.DETAILS_FAIL";
