export const PRODUCT_LIST_REQUEST = "PRODUCT.LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT.LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT.LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT.DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT.DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT.DETAILS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT.DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT.DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT.DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT.CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT.CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT.CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT.CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT.UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT.UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT.UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT.UPDATE_RESET";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT.CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT.CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT.CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT.CREATE_REVIEW_RESET";
